### ISSUE TITLE
authentication fails with linuxbrew python3

### ISSUE THREAD

**Issue by sidebo** [minrk/pamela#13]
I cannot authenticate myself ([PAM Error 7] Authentication failure upon ``python3 -m pamela -a `whoami`)``. Possibly this has to do with the way I installed python3. I'm on an slc6 machine and used linuxbrew for the install, I have /home/linuxbrew/ (python3 is here) and /home/usr1 /home/usr2 etc. Maybe I'm missing something else. Can you help?

**Comment by minrk** [comment]
It could be a PAM permission issue. The first thing to test might be to try running as root, and see if you can check your password as root.

**Comment by sidebo** [comment]
Thank you, that was indeed the issue!
