### ISSUE TITLE
Non-root using pamela to auth non-root

### ISSUE THREAD

**Issue by MincingWords** [minrk/pamela#9]
non-root user "foo" goes "python3.4 -m pamela -a foo", enters password, and it works. but if user foo then goes "python3.4 -m pamela -a bar" and enters bar's password (bar's un/pw works in console and ssh) then "[PAM Error 7] Authentication failure". Is there a way to configure so that this will work? trying to avoid running jupyterhub as root.

**Comment by minrk** [comment]
In a basic setup, a user must be able to read the password database to do this. On Ubuntu, this means being added to the `shadow` group. [These docs](https://github.com/jupyterhub/jupyterhub/wiki/Using-sudo-to-run-JupyterHub-without-root-privileges) cover setting up JupyterHub with local users without running as root.
